# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: &development
  adapter: mysql2
  encoding: utf8
  database: firstblog
  pool: 5
  username: root
  password: '198785'
  host: localhost
test:
  <<: *development
  database: firstblog

production:
  <<: *development
  database: pscrmdata_production
